### ISSUE TITLE
프로젝트 초기 설정

### ISSUE THREAD

**Issue by ge-um** [PohangTangerines/NalssiUttung#2]
## 📌 Issue
프로젝트 초기 설정을 진행합니다. 

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
- [x] 이슈 템플릿 생성
- [x] Pull Request 템플릿 생성
- [x] .DS_Store 올라가지 않도록 gitignore 수정
- [x] git attribute 추가
