### ISSUE TITLE
WeatherManager - 시간별 날씨 데이터 fetching function 만들기

### ISSUE THREAD

**Issue by 220v-K** [PohangTangerines/NalssiUttung#20]
## 📌 Issue

- 화면에서 날씨 정보를 띄우기 위해, 날씨 데이터를 불러오는 함수를 만들어요.
- 클라이언트 상에서 날씨 정보를 계속해서 불러오게 하는 것은 절대 좋은 구조가 아니지만, 우선 간단하게 구현해보기 위해 만들어요.
- 추후, 서버(Firebase Cloud Functions) 측으로 로직을 옮겨야 할 거에요.

## 📝 To-do
- [x] 현재 날씨(기온, 날씨, 최고/최저 온도)
- [x] 시간별 날씨(온도, 시간(3시간 간격), 날씨)
- [x] 주간 날씨(7일간의 날씨, 날짜, 최고/최저 온도), 습도)
- [x] 상세날씨(강수량, 바람, 가시거리)
- [ ] 지역 추가하기(지역정보 - 관측소 위치 기획팀에게 요청하기)
