### ISSUE TITLE
RealTimeLocationView 장소 정보 구현

### ISSUE THREAD

**Issue by Chang-Jin-Lee** [PohangTangerines/NalssiUttung#29]
📌 Issue

- 실시간 위치 정보를 표시하는 기능입니다.
- 현 위치가 제주 외부인 경우 제주공항 위치로 지정하시면 됩니다.
- 화살표 SF 심볼은 현재 위치에서 현재 위치의 날씨를 보는 경우에만 뜨고, 현재 위치와 다른 장소의 날씨를 보는 경우 사라지게 만드시면 됩니다.

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img width="400" src = "https://github.com/PohangTangerines/NalssiUttung/assets/54494793/38e4a434-2fe7-4ab7-a114-2ca89f753d6b">
||<img src = "">

## 📝 To-do
- [x] 실시간 위치 정보를 표시하기
- [x] 현 위치가 제주 외부인 경우 제주공항 위치로 지정하기
- [ ] 화살표 SF 심볼은 현재 위치에서 현재 위치의 날씨를 보는 경우에만 뜨고, 현재 위치와 다른 장소의 날씨를 보는 경우 사라지게 만들기
