### ISSUE TITLE
DailyWeatherView, WeeklyWeatherView, DetailedWeatherView 작업

### ISSUE THREAD

**Issue by 220v-K** [PohangTangerines/NalssiUttung#31]
## 📌 Issue

- DailyWeatherView, WeeklyWeatherView와 DetailedWeatherView의 디자인을 수정하고, 차트를 다시 그립니다.

## 📝 To-do
- [x] WeeklyWeatherView 디자인 명세에 맞게 수정
- [x] DetailedWeatherView 디자인 명세에 맞게 수정
- [x] DailyWeatherView 디자인 명세에 맞게 수정
- [x] WeeklyWeatherView 차트 수정
- [x] DailyWeatherView 차트 수정
