### ISSUE TITLE
LocationListView 모달, 리스트 WeatherKit 정보 연동

### ISSUE THREAD

**Issue by Chang-Jin-Lee** [PohangTangerines/NalssiUttung#32]
📌 Issue

LocationListView 모달, 리스트 WeatherKit 정보 연동

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
|검색기능 완성|<img src = "https://github.com/PohangTangerines/NalssiUttung/assets/54494793/f58a6657-b9ca-4cf5-81c0-2c3816c8f8b9">
|편집기능|<img src = "https://github.com/PohangTangerines/NalssiUttung/assets/54494793/e0657c77-0ed2-4f30-a63c-bab1ed5c13bc">

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [x] 검색 항목이 없으면 검색 결과가 없어요 띄우기
- [x] 각 항목마다 weatherBoxData task로 정보 가져오기
- [x] 항목 클릭시 Modal 띄우기
- [x] userdefault로 항목 정보 저장 및 불러오기
