### ISSUE TITLE
사용자 위치 저장 기능 추가

### ISSUE THREAD

**Issue by ge-um** [PohangTangerines/NalssiUttung#34]
📌 Issue

- LocationListView에서 현재는 저장된 모든 위치가 보입니다. 
- 저장 기능을 추가해서 추가한 위치 정보만 보이게 만듭니다. 

## 📸 ScreenShot
<!— 스크린샷을 넣고 기능에 대해 설명해주세요 ->
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
- [x] 저장 기능 추가
- [x] 모달에 추가 버튼 누르면 저장 되도록 만듬. 현재는 모달에 추가 버튼이 없음.
- [x] userDefault에 저장한 값을 뷰에 불러 오는 게 안 됨 -> userDefault에 값 자체가 잘못 전달 됨. location 값을 잘못 전달해서 그런 것 같은데 어떻게 해야할 지 모르겠음 ...... 
- [x] focusState를 이용해서 focusState를 해제시키고 뷰를 초기화시켜야 하는데 하는 법 모르겠음
- [x] 현재 location 정보가 연결이 됐다가 안 됐다가 함 -> location 정보를 잘못 전달하는 것 같음
