### ISSUE TITLE
QA 후 수정

### ISSUE THREAD

**Issue by ge-um** [PohangTangerines/NalssiUttung#44]
📌 Issue

- 에셋 gif로 수정
- LocationCard, CardModal 고정값 수정
- ModalView 디테일 수정
- 날씨 아이콘과 멘트 분기처리 수정
- 앱 이름 바꾸기

## 📸 ScreenShot
<!— 스크린샷을 넣고 기능에 대해 설명해주세요 ->
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [x] 에셋 gif로 수정
- [x] LocationCard, CardModal 고정값 수정
- [x] ModalView 디테일 수정
- [x] 날씨 아이콘과 멘트 분기처리 수정
- [x] 앱 이름 바꾸기
