### ISSUE TITLE
날씨정보 수정사항

### ISSUE THREAD

**Issue by Chang-Jin-Lee** [PohangTangerines/NalssiUttung#45]
📌 Issue
- 날씨정보 주소에 대한 정보가 카드로 보여지면 너무 느려서 안됨
- 현재 searchText가 여러군데 있어서 검색바가 느림
- 이미 추가된 항목에 추가 버튼이 나옴

## 📸 ScreenShot
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
- [x] 날씨정보 주소에 대한 정보를 String 1차원 배열로 보여주기
- [x] searchText 최적화해서 검색바 빠르게 하기
- [x] 이미 추가된 항목에 추가 버튼 안나오게 하기
