### ISSUE TITLE
위젯 구현

### ISSUE THREAD

**Issue by ge-um** [PohangTangerines/NalssiUttung#63]
📌 Issue

<!— 이슈에 대해 간략하게 설명해주세요 —> 
- widget small size를 제작합니다. 

## 📸 ScreenShot
<!— 스크린샷을 넣고 기능에 대해 설명해주세요 ->
|기능|스크린샷|
|:--:|:--:|
|widget 1번|<img width="158" alt="Group 517167247@2x" src="https://github.com/user-attachments/assets/bd4620e9-e444-4aaf-936e-6a95bc0d8f4d">
|widget 2번|<img width="158" alt="Group 517167251@2x" src="https://github.com/user-attachments/assets/ab23da01-1964-49a1-b878-8dabb805b01c">

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [x] widget 1번 view 제작
- [x] widget 2번 view 제작
- [ ] 현재 날씨 데이터에 따라 애니메이션 연결
- [x] 현재 지역 데이터에 따라 지역 연결
- [x] 현재 날씨 데이터에 따라 날씨 연결
- [x] 현재 날씨 데이터에 따라 날씨 문구 연결
- [x] 1시간마다 갱신
- [x] 유저가 지역을 변경하면 즉시 변경 후 갱신
