### ISSUE TITLE
[Fix] 버그 개선

### ISSUE THREAD

**Issue by ge-um** [PohangTangerines/NalssiUttung#67]
📌 Issue

- 현재 위치가 제주가 아닌 경우, 현재 위치의 날씨를 불러오고 있습니다.
- 또한 주소 정보가 간혹 보이지 않는 경우가 있습니다. 
- 위젯의 날씨와 앱의 날씨가 일치하지 않는 경우가 있습니다. 

## 📸 ScreenShot
<!— 스크린샷을 넣고 기능에 대해 설명해주세요 ->
|기능|스크린샷|
|:--:|:--:|
|위젯 날씨와 앱 날씨 일치하지 않는 경우|![Simulator Screen Recording - iPhone 16 - 2024-12-12 at 23 50 20](https://github.com/user-attachments/assets/8c108852-7c7e-4f62-a8e5-67bb76cb66cc)
|주소 정보가 간혹 보이지 않는 경우|![Simulator Screen Recording - iPhone 16 - 2024-12-12 at 23 53 42](https://github.com/user-attachments/assets/679a2ae2-ef87-4b3b-9d04-c75ac3194c24)

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [x] 제주가 아닌 경우 제주공항의 정보 가져오기
- [x] 주소 정보가 보이지 않는 경우 개선
- [ ] 위젯의 날씨와 앱의 날씨 일치
