### ISSUE TITLE
[Fix] 앱 크래시 오류 개선

### ISSUE THREAD

**Issue by ge-um** [PohangTangerines/NalssiUttung#69]
📌 Issue

<!— 이슈에 대해 간략하게 설명해주세요 —> 
- Location 정보를 받아오는 과정에서 발생하는 크래시 오류를 개선합니다. 
- 이외에 자잘한 버그를 개선합니다. 
## 📸 ScreenShot
<!— 스크린샷을 넣고 기능에 대해 설명해주세요 ->
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
<!- 진행할 작업에 대해 적어주세요 ->
- [ ] 크래시 오류 개선
- [ ] 위치 정보를 받아올 때 뒤의 현재 위치를 나타내는 화살표와 추가 버튼 지우기
- [ ] 현 위치를 받아올 때 바로 화면에 뜨지 않는 문제 개선
