### ISSUE TITLE
배포 이후 버그 개선

### ISSUE THREAD

**Issue by ge-um** [PohangTangerines/NalssiUttung#71]
📌 Issue

- 배포 후 생긴 문제를 개선합니다. 

## 📸 ScreenShot
<!— 스크린샷을 넣고 기능에 대해 설명해주세요 ->
|기능|스크린샷|
|:--:|:--:|
||<img src = "">
||<img src = "">

## 📝 To-do
- [ ] 권한 설정에서 변경 시 권한 요청 창이 다시 뜨는 문제 개선하기
- [ ] 제주시가 아니어서 현재 위치와 기기 위치가 다를 때 날씨 목록에서 추가 버튼 활성화시키지 않기
- [ ] 위젯 데이터 불러오지 못하는 문제 개선
